version: "2"

services:
  demo1:
    build:
      context: ./demo1
      args:
        - JAR_FILE=build/libs/*.jar
    ports:
      - "8080:8080"
    container_name: demo1
    networks:
      spring-boot-docker-demo-network:
        aliases:
          - demo1.taonaw.org

  demo2:
    build:
      context: ./demo2
      args:
        - JAR_FILE=build/libs/*.jar
    ports:
      - "8081:8080"
    container_name: demo2
    networks:
      spring-boot-docker-demo-network:
        aliases:
          - demo2.taonaw.org

networks:
  spring-boot-docker-demo-network:
    external: true
