version: "2"

services:
  demo1:
    build:
      context: ./demo1
      args:
        - JAR_FILE=build/libs/*.jar
    container_name: demo1
    ports:
      - "8080:8080"
    depends_on:
      - demo2
    networks:
      - spring-boot-docker-demo-network

  demo2:
    build:
      context: ./demo2
      args:
        - JAR_FILE=build/libs/*.jar
    container_name: demo2
    expose:
      - "8080"
    networks:
      - spring-boot-docker-demo-network

networks:
  spring-boot-docker-demo-network:
    external: true
